index:
    path: /
    controller: 'App\Controller\DefaultController::index'

error_404:
    path: /seite-nicht-gefunden
    controller: 'App\Controller\DefaultController::error404'

error_500:
    path: /interner-fehler
    controller: 'App\Controller\DefaultController::error500'

missions:
    path: /missionen/{slug}
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: null

missions_static:
    path: /missionen
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: null

missions_kolonie-9:
    path: /missionen/kolonie-9
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: kolonie-9

missions_tephra-hoehle:
    path: /missionen/tephra-hoehle
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: tephra-hoehle

missions_kolonie-6:
    path: /missionen/kolonie-6
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: kolonie-6

missions_sumpf-von-satorl:
    path: /missionen/sumpf-von-satorl
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: sumpf-von-satorl

missions_wald-von-makna:
    path: /missionen/wald-von-makna
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: wald-von-makna

missions_grenzdorf:
    path: /missionen/grenzdorf
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: grenzdorf

missions_eryth-meer:
    path: /missionen/eryth-meer
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: eryth-meer

missions_alcamoth:
    path: /missionen/alcamoth
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: alcamoth

missions_berg-valak:
    path: /missionen/berg-valak
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: berg-valak

missions_schwerttal:
    path: /missionen/schwerttal
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: schwerttal

missions_festung-galahad:
    path: /missionen/festung-galahad
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: festung-galahad

missions_gefallener-arm:
    path: /missionen/gefallener-arm
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: gefallener-arm

missions_mechonis-hallen:
    path: /missionen/mechonis-hallen
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: mechonis-hallen

missions_zentralfabrik:
    path: /missionen/zentralfabrik
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: zentralfabrik

missions_agniratha:
    path: /missionen/agniratha
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: agniratha

missions_gefaengnisinsel-2:
    path: /missionen/gefaengnisinsel-2
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: gefaengnisinsel-2

missions_bein-des-bionis:
    path: /missionen/bein-des-bionis
    controller: 'App\Controller\MissionsController::index'
    defaults:
        slug: bein-des-bionis

persons:
    path: /personen
    controller: 'App\Controller\PersonsController::index'

persons_spoiler:
    path: /personen/personen-nach-mechonis-kern
    controller: 'App\Controller\PersonsController::spoilerPersons'

maps:
    path: karten
    controller: 'App\Controller\MapsController::index'

gear:
    path: item-box/ausrustung
    controller: 'App\Controller\GearController::gear'

weapons:
    path: item-box/waffen
    controller: 'App\Controller\GearController::weapons'

chests:
    path: item-box/truhen
    controller: 'App\Controller\ChestsController::index'

jewels:
    path: item-box/juwelen
    controller: 'App\Controller\ItemBoxController::jewels'

etherveins:
    path: item-box/atheradern
    controller: 'App\Controller\ItemBoxController::etherveins'

important_items:
    path: item-box/wichtiges
    controller: 'App\Controller\ItemBoxController::important'

collection:
    path: item-box/kollektion
    controller: 'App\Controller\CollectionsController::index'

merchants:
    path: item-box/handler
    controller: 'App\Controller\MerchantsController::index'

collectionitems:
    path: item-box/sammelitems/{name}
    controller: 'App\Controller\ItemBoxController::collectionItems'
    defaults:
        name: null

collectionitems_static:
    path: item-box/sammelitems
    controller: 'App\Controller\ItemBoxController::collectionItems'
    defaults:
        name: null

collectionitems_shulk:
    path: item-box/sammelitems/shulk
    controller: 'App\Controller\ItemBoxController::collectionItems'
    defaults:
        name: shulk

collectionitems_reyn:
    path: item-box/sammelitems/reyn
    controller: 'App\Controller\ItemBoxController::collectionItems'
    defaults:
        name: reyn

collectionitems_sharla:
    path: item-box/sammelitems/sharla
    controller: 'App\Controller\ItemBoxController::collectionItems'
    defaults:
        name: sharla

collectionitems_dunban:
    path: item-box/sammelitems/dunban
    controller: 'App\Controller\ItemBoxController::collectionItems'
    defaults:
        name: dunban

collectionitems_melia:
    path: item-box/sammelitems/melia
    controller: 'App\Controller\ItemBoxController::collectionItems'
    defaults:
        name: melia

collectionitems_riki:
    path: item-box/sammelitems/riki
    controller: 'App\Controller\ItemBoxController::collectionItems'
    defaults:
        name: riki

collectionitems_person7:
    path: item-box/sammelitems/person 7
    controller: 'App\Controller\ItemBoxController::collectionItems'
    defaults:
        name: person 7

chainattacks:
    path: guides/angriffsketten/
    controller: 'App\Controller\GuidesController::chainAttacks'

characterguides_dunban:
    path: guides/charakter-dunban
    controller: 'App\Controller\GuidesController::character'
    defaults:
        character: dunban

characterguides_shulk:
    path: guides/charakter-shulk
    controller: 'App\Controller\GuidesController::character'
    defaults:
        character: shulk

characterguides_fiora:
    path: guides/charakter-fiora
    controller: 'App\Controller\GuidesController::character'
    defaults:
        character: fiora

characterguides_reyn:
    path: guides/charakter-reyn
    controller: 'App\Controller\GuidesController::character'
    defaults:
        character: reyn

characterguides_person7:
    path: guides/charakter-person7
    controller: 'App\Controller\GuidesController::character'
    defaults:
        character: person7

characterguides_melia:
    path: guides/charakter-melia
    controller: 'App\Controller\GuidesController::character'
    defaults:
        character: melia

characterguides_riki:
    path: guides/charakter-riki
    controller: 'App\Controller\GuidesController::character'
    defaults:
        character: riki

characterguides_sharla:
    path: guides/charakter-sharla
    controller: 'App\Controller\GuidesController::character'
    defaults:
        character: sharla

skills:
    path: /fertigkeiten
    controller: 'App\Controller\SkillsController::index'

colony6:
    path: guides/kolonie-6-ausbau/
    controller: 'App\Controller\Colony6Controller::index'

gemcrafting:
    path: guides/schmieden
    controller: 'App\Controller\GuidesController::gemCrafting'

storyfights:
    path: guides/handlungskampfe
    controller: 'App\Controller\StoryFightsController::index'

extraskilltrees:
    path: guides/extra-talente
    controller: 'App\Controller\GuidesController::skillTrees'

giftguide:
    path: guides/anleitung-sammelitems-verschenken/
    controller: 'App\Controller\GuidesController::gifts'

harmonymeetings:
    path: extras/harmonie-gesprache/
    controller: 'App\Controller\ExtrasController::harmonyMeetings'

trophies:
    path: extras/trophaen/
    controller: 'App\Controller\ExtrasController::trophies'
